### PR TITLE
Update pronouns.tab to include "computer"

### PR DESCRIPTION
**Pull request by Charlotteis**
Hi! Firstly this is an awesome website and I'm glad I can send my pronouns to people who struggle to understand their use case.

This PR adds 'computer' into the database. It may seem a little silly, but I like to use this mixed with 'their' pronouns.

Thanks again,
Charlotte :computer:

### CODE REVIEW

**Comment by morganastra** [comment]
Hey, totally happy to include this, but the columns need to be separated by tab characters - please fix that and I'll merge it.

**Comment by Charlotteis** [comment]
@morganastra thanks! Have updated :)

**Comment by morganastra** [comment]
That's still space separated, but you need literal tab characters. Your editor might be configured to convert tabs to spaces, if so you'll need to disable that setting on the .tab file type.

**Comment by Charlotteis** [comment]
@morganastra Sorry, I did this using GitHub in the browser which I assumed would do the right thing. I will update, thank you.

**Comment by Charlotteis** [comment]
Sorry it took so long to get to this, thanks for your help @morganastra. I converted my Tabs to Spaces :)

**Comment by morganastra** [comment]
as a guideline I'll generally only accept pronouns that are a well-formed english pronoun set (all pronouns from the set being plausible declensions of the same word) and for which there is some evidence that a few people actually use them. you are of course always free to write out a set of pronouns (or any words) manually if you just want to see what they look like in the example sentences, e.g. http://pronoun.is/computer/computer/their/theirs/theirselves or even [this whole story](http://pronoun.is/she/or%20they,%20those%20ships%20who%20were%20docked%20and%20still%20equipped%20with%20ancillaries,%20arranged%20to%20share%20the%20duty%20of%20monitoring%20our%20guest%20as%20it%20fit%20into%20their%20routines;%20that%20was%20the%20agreement,%20despite%20it%20being%20less%20convenient%20for%20me%20to%20participate%20at%20all,%20on%20the%20grounds%20that%20certain%20visitors%20might%20prefer%20a%20constant%20individual%20companion%20to%20what%20might%20seem,%20depending%20on%20their%20past%20experiences,%20to%20be%20undue%20attention%20from%20every%20soldier%20they%20passed.%20As%20usual,%20then,%20I%20took%20the%20first%20shift/the%20one%20possession%20of%20hers%20that%20Station%20Security%20hadn't%20confiscated,%20a/knowingly%20left%20with%20her.%20What%20a%20Presger%20frisbee%20might%20do%20or%20even%20look%20like%20I%20couldn't%20say.%20She%20hadn't%20seemed%20the%20sort%20to%20have%20alien%20technology,%20but,%20then%20again,%20neither%20had%20I/another%20unremarkable%20stranger,%20quite%20a%20ways%20down%20the%20concourse,%20who%20caught%20it%20with%20a%20degree%20of%20coordination%20that%20most%20would%20have%20overlooked.%20It%20did%20not%20escape%20my%20notice,%20however.%20"Cousin,"%20I%20said,%20enough%20to%20convey%20(unless%20our%20visitor%20were%20quite%20ignorant,%20but,%20of%20course,%20at%20this%20point%20I%20was%20certain%20that%20she%20couldn't%20be)%20both%20that%20I%20knew%20what%20she%20was%20not%20and%20that%20I%20was%20giving%20her%20the%20benefit%20of%20the%20doubt%20as%20to%20what,%20or%20who,%20she%20was)

**Comment by Charlotteis** [comment]
That totally makes sense, thanks ✨

**Pull request closed without merging**
