### PR TITLE
Add more pronouns! 👏🏿👏🏾👏🏽👏🏼👏🏻

### PR DESCRIPTION
**Pull request by swampservers**
Thank you SO MUCH for creating this service, I've gotten SOOOO tired of being misgendered on Reddit and adding this link to my profile has helped me greatly! However, I noticed some other folx (#100 #105 #112) have suffered from a lack of representation due to the limited number of pronouns available on this repository.

Many of us have created pull requests to add our own personal pronouns to this dataset, but I worry that some **users who lack the technical knowledge to do this may be marginalized**! I hope that in the future, before creating oppressive structures such as the "pronoun inclusion policy", the authors will partake in a comprehensive ethics review to ensure that many folx with a diverse set of lived experiences can have their voices heard so as to prevent potential inequities such as this. I also believe that the "unwieldy" solution of using a long URL is inadequate as it will make some non-binary people feel marginalized.

For now, I have expanded this service with a very inclusive selection of pronouns to ensure that many more people will be represented. As Karl Marx once said, "From each according to zqyrs ability, to each according to xjibs need."

Unfortunately, while creating this PR I discovered that GitHub itself has placed an unjust and transphobic limitation on the size of our commune's pronoun list. I've added as many pronouns as GitHub permits - but I believe that files, like people, are healthy at any size, and GitHub should rethink this fascist policy so that all 7 billion members of peoplekind can achieve equal representation.

*Thanks for contributing! Please check the following things before submitting your PR :)*

  - [x] PR message includes a link to the relevant issue(s) 💁‍♀️🖇️🧾
  - [x] Commit messages are well-formatted
  (please follow [this guide](https://chris.beams.io/posts/git-commit/)) 📝📐
  - [x] New features have test coverage 📋☑️☑️☑️
  - [x] The app boots and pronoun pages are served correctly 
  (try `lein ring server`) 👩‍💻🚀

### CODE REVIEW

**Review by ivanka2012 — APPROVED** [review]
LGTM!

**Comment by DonaldTsang** [comment]
You guys might want to collaborate with others who are trying to create a wiki for the pronouns.
https://docs.google.com/document/d/1Tn3_UuHB-1JpOKFGBxF7PFtSOTbzVKy5S47geiOOcTE/edit
Also in the documents, there are sexual orientations and genders for you to choose!

**Comment by DonaldTsang** [comment]
@swampservers apologies but I do think that after looking at the files, that I think there are discrepancies between your table and the resources that I have found. Would it be possible to provide some citations on your table?

**Comment by swampservers** [comment]
What do you mean, citations? Surely you're not implying that non-binary folx need to PROVE that their identities are valid?! Our pronoun table gives maximum coverage of folx' identities to avoid any possible marginalization. You don't want to DISCRIMINATE against any non-binary people (potentially of color or differently abled) do you?

**Review by alii — APPROVED** [review]

**Review by ven — APPROVED** [review]

**Comment by NoClient9179** [comment]
no way

**Comment by trn1ty** [comment]
I would encourage any moderators to look at this post carefully. Although good faith should be assumed most of the time, there are some concerning posts on [their Steam community](https://steamcommunity.com/groups/swampservers/announcements/listing) that suggest they're pulling a little prank here (see also the attached image). They use a lot of terms that aren't really used except by members of the right wing to poke fun at marginalized people ("folx", "peoplekind"), they use a Karl Marx quote randomly in which they've swapped around some pronouns, and they've called Github fascist which is a bizarre accusation to throw around in the middle of a pull request, all of which are traits of the center-left and left according to the political right. Consider also that it would be very easy to slip off-color pronouns into a commit of this size. 

The process of making a Github PR is not very complicated and there are many people you can contact directly for help. Smaller commits are preferable.

Warning: ableist language ahead in the attached screenshot.

Screenshot_2021-02-18 Steam Community Group Swamp Servers

**Pull request closed without merging**
